### ISSUE TITLE
Prepend optional user-specified string to title bar also (feature request!)

### ISSUE THREAD

**Issue by yellowfeet** [Aaron-P/HostnameTitleBar#1]
Would love to be able to distinguish between my firefox profiles by prepending a chosen short string before the hostname in the title bar (which I'd obviously make different for each installation of the extension).

Could probably find another extension to do this, of course, but I'm all for minimalism...

**Comment by Aaron-P** [comment]
If extension settings are per-profile then I can probably do something fairly easily; I only use a single profile so I'm not certain that's the case.  My first idea would be to make the entire thing an editable template with placeholders for various pieces of info, e.g. {title} to show the title or {hostname} for the host name.  The only thing is that I really want to keep it as simple as possible for most users, so I'll have to think for a little while on how to handle that.

**Comment by yellowfeet** [comment]
They're definitely per-profile. If you want the same extension on multiple profiles, you have to install it multiple times. This compartmentalisation is why I love profiles :)

A template would be the most flexible solution but I think you're right - simplicity is a good thing - and I'm not sure how much Firefox actually allows you to monkey with the window title anyway... but then I don't write extensions (yet!)

Really, all I'd be looking for is a simple string prefix that I could set per instance, but that might just be me!

**Comment by Aaron-P** [comment]
I've been working on the new version that should be able to do what you want.  Wanted to see if you had any input.

![capture](https://user-images.githubusercontent.com/744119/50728692-adc55980-10f3-11e9-8e28-7c5122691a38.PNG)

**Comment by yellowfeet** [comment]
Looks good. Thank you for working on it!
As I said before, I probably wouldn't use anything other than plain text and {hostname} in my Template but I don't see why you shouldn't offer more - some folks might find it useful.

**Comment by Aaron-P** [comment]
Fixed by c75bdc356d5246e7b1beaee73f5bdc9558bdb82d.
