### ISSUE TITLE
Any plan for Chrome/Chromium ? 

### ISSUE THREAD

**Issue by Remonli** [Aaron-P/HostnameTitleBar#4]
Do you have any plan for chrome version ？ I searched in chrome store but just found
a very old  one without any maintainence. Thank you!

**Comment by Aaron-P** [comment]
Chrome/Chromium doesn't have the titlePreface property on
browser.windows.update; that is currently a unique feature of the
Firefox web extension api.  Because of that the way this extension works
is currently not possible in Chrome/Chromium.

**Comment by kantlivelong** [comment]
Hey @Remonli,

[Url in title](https://chrome.google.com/webstore/detail/url-in-title/ignpacbgnbnkaiooknalneoeladjnfgb) is very similar. I recently switched to Firefox from Chromium and that's what I had been using.

**Comment by Remonli** [comment]
@Aaron-P  Thank you for explain. 

@kantlivelong Great ! Thank you for your suggestion.

**Comment by Aaron-P** [comment]
Closing this unless there are changes to the Chromium api.
