### ISSUE TITLE
Not working in Firefox 113 using default settings

### ISSUE THREAD

**Issue by redactedscribe** [Aaron-P/HostnameTitleBar#6]
![firefox_2023-05-18_12-01-48](https://github.com/Aaron-P/HostnameTitleBar/assets/25013746/62796812-4acd-44ed-98a9-d65d414cd4e7)

![firefox_2023-05-18_12-03-12](https://github.com/Aaron-P/HostnameTitleBar/assets/25013746/41a4d5b6-b335-47fc-8451-9a9630defb14)

Firefox 113.0.1
Windows 11 22621

**Comment by Aaron-P** [comment]
If your 2nd screenshot is hovering over the tab you won't be able to see the modified window title by doing that. The extension works by using the titlePreface option of [windows.update](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/windows/update) and only changes the title of the window. If you look at the window title using something like Process Explorer, or by setting `browser.tabs.inTitlebar = 0` in about:config, you should be able to see the modified title.

![image](https://github.com/Aaron-P/HostnameTitleBar/assets/744119/8d784083-2d30-4f90-8287-5d9255630012)

**Comment by redactedscribe** [comment]
You're correct, I see it now. It does indeed work as you describe. Sorry about that!
